/**
 * Device-local cache of generated article summaries.
 *
 * Summaries used to live only in the (non-persisted) feeds store, so every
 * reload re-hit the paid LLM route for articles already summarized — slow and
 * billed twice for nothing.
 *
 * Entries are versioned by {@link SUMMARY_PROMPT_VERSION}: the prompt and the
 * length-banding decide what a summary looks like, so when they change, cached
 * summaries generated by the old rules must not be served. Bump the constant in
 * the same commit as any prompt/banding change and stale entries are ignored
 * (and pruned) automatically.
 */

/**
 * Bump when the summarizer's prompt or length bands change.
 * v2 — length-scaled summaries: full-article input (was truncated at 6k chars)
 *      plus word-count-banded prose/bullet targets.
 * v3 — teaser-only feeds are summarized from the recovered full article, so
 *      summaries cached from the teaser must not be served.
 */
export const SUMMARY_PROMPT_VERSION = 3;

const STORAGE_KEY = 'readest_feed_summaries';
/** Keep the most recent N summaries; older entries are pruned on write. */
const MAX_ENTRIES = 300;

export type SummaryFormat = 'prose' | 'bullets';

export interface CachedSummary {
  summary: string;
  format: SummaryFormat;
  /** True when the model judged the article adds nothing beyond the blurb. */
  redundant?: boolean;
}

interface StoredSummary extends CachedSummary {
  v: number;
  at: number;
}

type SummaryMap = Record<string, StoredSummary>;

const load = (): SummaryMap => {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as SummaryMap;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

const persist = (map: SummaryMap): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(map));
  } catch {
    /* storage full / unavailable — summaries just won't survive the reload */
  }
};

/** Every still-valid cached summary, for seeding the store on the client. */
export const loadSummaries = (): Record<string, CachedSummary> => {
  const map = load();
  const out: Record<string, CachedSummary> = {};
  for (const [id, entry] of Object.entries(map)) {
    if (entry?.v === SUMMARY_PROMPT_VERSION && (entry.summary || entry.redundant)) {
      out[id] = { summary: entry.summary, format: entry.format, redundant: entry.redundant };
    }
  }
  return out;
};

export const saveSummary = (articleId: string, entry: CachedSummary): void => {
  if (!articleId || (!entry.summary && !entry.redundant)) return;
  const map = load();
  map[articleId] = { ...entry, v: SUMMARY_PROMPT_VERSION, at: Date.now() };
  // Drop entries from older prompt versions while we're here, then LRU-trim.
  for (const [id, e] of Object.entries(map)) {
    if (e.v !== SUMMARY_PROMPT_VERSION) delete map[id];
  }
  const ids = Object.keys(map);
  if (ids.length > MAX_ENTRIES) {
    ids
      .sort((a, b) => (map[a]!.at ?? 0) - (map[b]!.at ?? 0))
      .slice(0, ids.length - MAX_ENTRIES)
      .forEach((id) => delete map[id]);
  }
  persist(map);
};
